-- Safe migration: preserves existing data and adds new columns for enhanced event booking features.

CREATE TABLE IF NOT EXISTS events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(255) NULL,
  date DATETIME NOT NULL,
  total_seats INT NOT NULL DEFAULT 100,
  available_seats INT NOT NULL DEFAULT 100,
  price DECIMAL(10,2) NULL DEFAULT 0,
  img VARCHAR(255) NULL,
  image VARCHAR(255) NULL,
  category VARCHAR(255) NULL,
  vip_price DECIMAL(10,2) NULL DEFAULT 0,
  standard_price DECIMAL(10,2) NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bookings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  event_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  mobile VARCHAR(20) NULL,
  quantity INT NULL,
  tickets INT NULL,
  ticket_category VARCHAR(20) NULL DEFAULT 'standard',
  total_amount DECIMAL(10,2) NULL DEFAULT 0,
  booking_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50) NOT NULL DEFAULT 'confirmed'
);

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS location VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS vip_price DECIMAL(10,2) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS standard_price DECIMAL(10,2) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_seats INT NULL DEFAULT 100,
  ADD COLUMN IF NOT EXISTS available_seats INT NULL DEFAULT 100,
  MODIFY COLUMN total_seats INT NOT NULL DEFAULT 100,
  MODIFY COLUMN available_seats INT NOT NULL DEFAULT 100;

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS ticket_category VARCHAR(20) NULL DEFAULT 'standard',
  ADD COLUMN IF NOT EXISTS total_amount DECIMAL(10,2) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mobile VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS booking_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) NOT NULL DEFAULT 'confirmed',
  MODIFY COLUMN booking_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY COLUMN status VARCHAR(50) NOT NULL DEFAULT 'confirmed';